//= output "caught\nException\n0: testThrowFromNative(Bool): 9\n1: main(): 5\nafter\nend\n"

fun main() {
  do {
    try testThrowFromNative(true);
    assert(false);
  } catch e: Exception {
    println("caught");
    e.printStackTrace();
    assert(true);
  }

  println("after");
  try! testThrowFromNative(false);
  println("end");
}
