//= vm-args "--gc-verify"
//= stdout "b: 19\na: 15\nmain: 5\n"

fn main() {
  let e = a();

  // this should test if backtrace in Exception is created the right way
  // by retrieveStackTrace (as Array[Int32])
  std::forceCollect();

  e.printStacktrace();
}

fn a(): std::Stacktrace {
  return b();
}

fn b(): std::Stacktrace {
  return std::Stacktrace::new();
}